---
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab
    restart: unless-stopped
    shm_size: "256m"

    ports:
      - "${APP_PORT_PREFIX:-15}080:80" # HTTP
      - "${APP_PORT_PREFIX:-15}443:443" # HTTPS
      - "${APP_PORT_PREFIX:-15}022:22" # SSH

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL:-https://gitlab.mydomain.com}'

        gitlab_rails['time_zone'] = '${TIME_ZONE:-UTC}'

        # Initial root configuration
        gitlab_rails['initial_root_password'] = '${ROOT_PASSWORD:-Backstab-Ladies3-Buddhist}'
        gitlab_rails['initial_root_email'] = '${ROOT_EMAIL}'

        # SSH on non-standard port
        gitlab_rails['gitlab_shell_ssh_port'] = ${APP_PORT_PREFIX:-15}022
        # Reduce memory pressure a bit
        puma['worker_processes'] = 2
        sidekiq['concurrency'] = 10

    volumes:
      - ${APP_DIR:-/volumes/containers/gitlab}/config:/etc/gitlab
      - ${APP_DIR:-/volumes/containers/gitlab}/logs:/var/log/gitlab
      - ${APP_DIR:-/volumes/containers/gitlab}/data:/var/opt/gitlab
