---
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.11.3
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "${APP_PORT_PREFIX:-17}080:80"
      - "${APP_PORT_PREFIX:-17}081:81"
      - "${APP_PORT_PREFIX:-17}443:443"
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${APP_DIR:-/volumes/containers/nginx-proxy-manager}/data:/data
      - ${APP_DIR:-/volumes/containers/nginx-proxy-manager}/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    driver: bridge
